name: Docs

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel'
    - run: nimble genDoc
    
