name: Docs

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-devel-latest
        
    - name: Setup Nim Enviroment
      uses: actions/checkout@master
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel'
      
    - name: Generate Documentation
      run: nimble genDoc
    
    - name: deploy docs
      uses: ./
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        remote_url: https://github.com/ire4ever1190/nim-opentmdb.git

