name: Docs

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-devel-latest
    - uses: actions/checkout@master
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel'
    - run: nimble genDoc
    
